AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  EnvName:
    Type: String

Resources:
  ApiHandler:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs14.x
      CodeUri: .
      Handler: aws-lambda-main.handler
      Events:
        ApiGatewayIntegration1:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ApiGatewayIntegration2:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          ENV_NAME: !Ref EnvName
    Metadata:
      BuildMethod: makefile
